
default: -r support -r step_definitions
##default:  --profile pom
##pom: -r support -r features/step_definitions features --profile common_formatters --format rerun --out log/rerun.txt

##common_formatters: >
 ##--format html --out log/cucumber.html
pom: features -t @test -f html -o features_report.html